### PR TITLE
Created a Simple Digital Clock

### LINKED ISSUE #133: Create a Simple Clock
- Develop an HTML structure to display a digital clock.
- Use CSS to style the clock's appearance.
- Implement JavaScript to update the time in real-time.

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
fixes #133

### CODE REVIEW

**Comment by UdaySagar-Git** [comment]
@simranlotey please let me know if it requires any changes
also please kindly add` hacktoberfest-accepted` to this pr

**Comment by simranlotey** [comment]
@UdaySagar-Git You should create a new directory that contains the directory name of the issue name and the code inserted in the directory.

**Comment by UdaySagar-Git** [comment]
sure @simranlotey i will work on this

**Comment by UdaySagar-Git** [comment]
@simranlotey updated the pull request ! please let me know if it requires any more edits

**Pull request merged**
